# Site settings
baseurl = "https://geo-nord.github.io/"
languageCode = "fr"
title = "GPS Maze Adventures - GeoNord"
theme = "syna"
enableGitInfo = true
version = "0.17.3"
DefaultContentLanguage = "fr"

[languages]
  [languages.fr]
    title = "GPS Maze Adventures - GeoNord"
    weight = 1
  [languages.en]
    title = "GPS Maze Adventures - GeoNord"
    weight = 2

# Google Analytics tracking
googleAnalytics = ""

disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "JSON"]

[frontmatter]
date = ["date", "lastmod"]
lastmod = ["lastmod", ":git", "date"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
     unsafe = true

[params]
  name = "GPS Maze Adventures - GeoNord - Association Geocaching Hauts de France"
  description = "GPS Maze Adventures - GeoNord - Association Geocaching Hauts de France"
  DefaultContentLanguage = "fr"
  customCSS = "css/custom.css"

  [params.style]
    #background = "secondary"

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
    favicon = "favicon.iso"
    favicon_ico_sizes = "16x16 32x32"
    favicon_png = "favicon.png"

  # Piwik tracking
  [params.analytics.piwik]
    #url = ""
    #id = ""
    #domain = "" # Track subdomains via "*.example.com"
    # Optional hash for integrity check
    #hash = ""

  # Optional, global disable switch for fontawesome related files
  # For custom fontawesome js files use the custom.js method
  [params.fontawesome]
    disabled = false
    pro = false

  [params.colors]
    primary = "#343538"
    secondary = "#868e96"
    success = "#008f54"
    info = "#00c9dc"
    warning = "#fdf314"
    danger = "#dc1200"
    light = "#f8f9fa"
    dark = "#343a40"

# main/prepend/postpend menus are displayed in nav fragment.
# Keep an eye out for updates. These will be moved out to make navbar more
# configurable.
[[menu.main]]
  url = "/"
  name = "Home"
  weight = 10

[[menu.main]]
  url = "/gps-maze"
  name = "GPS Maze"
  weight = 20

[[menu.main]]
  url = "/history"
  name = "History"
  weight = 30

[[menu.main]]
  url = "/contact"
  name = "Contact"
  weight = 40

[[menu.footer]]
  url = "https://www.geocaching.com/p/?u=Geo-Nord"
  name = "Profil Geocaching"
  weight = 10

[[menu.footer]]
  url = "https://photos.google.com/share/AF1QipOZzeW_8JQAYPpkQ-vxduRIGLAX4ZoUVgwjTRgViQuZ7GxLk3Hucwn7LXnkNov9xQ?key=YkE0cUo2YnkzYVZsdjdvTFREX1JZT0l5RkZyZUFB"
  name = "Photos 2022"
  weight = 20

[[menu.footer]]
  url = "https://github.com/Geo-Nord/labcaches_gpx"
  name = "Labcaches GPX"
  weight = 30


[[menu.footer_social]]
  weight = 10
  name = "facebook"
  pre = "fab fa-facebook"
  url = "https://www.facebook.com/GeoNord22/"

[[menu.footer_social]]
  weight = 20
  name = "youtube"
  pre = "fab fa-youtube"
  url = "https://www.youtube.com/watch?v=BFCIsWKDkbU"

# See issue https://github.com/okkur/syna/issues/859 
[minify]
  disableJS = true

